# Use a big scrollback
set -g history-limit 200000

# Terminal settings
set -g xterm-keys on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Mouse support
set -g mouse on

# Don't exit the copy-mode on mouse copy
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-no-clear "pbcopy" \; send -X clear-selection
bind -T copy-mode DoubleClick1Pane \
  send -X select-word \;\
  send -X copy-pipe-no-clear "pbcopy" \;\
  run-shell "sleep 0.5; tmux send -X clear-selection"

# Notifications: Activity
set -g monitor-activity on
set -g visual-activity off

# Notifications: Visual bell
set -g monitor-bell on
set -g visual-bell on
set -g bell-action any

# Notifications: Timing
set -g status on
set -g status-interval 2
set -g display-time 3000

# Faster escape from prefix sequences
set -sg escape-time 5

# More intuitive splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# PageUp enters scroll mode
bind -n PageUp copy-mode -u

# Panel: left side
# No gaps between "tabs"
set -g window-status-separator ""

# Base style: theme defaults
set -g window-status-style fg=default,bg=default
set -g window-status-current-style reverse
set -g window-status-bell-style fg=black,bg=yellow
set -g window-status-activity-style fg=default,bg=default

# Show default flags, but avoid extra space when none.
set -g window-status-format \
" #I:#W#{?window_activity_flag,*,#{?window_bell_flag,!,#{?window_zoomed_flag,Z, }}} #[default]"
set -g window-status-current-format \
" #I:#W#{?window_activity_flag,*,#{?window_bell_flag,!,#{?window_zoomed_flag,Z, }}} #[default]"

# Panel: right size
set -g status-right-length 150
set -g status-right '#{s|#{HOME}|~|:pane_current_path}'

# Windows
bind-key -r < swap-window -t :- \; previous-window
bind-key -r > swap-window -t :+ \; next-window
bind-key [ previous-window
bind-key ] next-window

# Reload config quickly
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
